# Generated by Django 2.2.2 on 2019-07-18 15:15

import apps.base.utils
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentAdvt',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(default=apps.base.utils.custom_uuid, editable=False, max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('checkup_id', models.CharField(editable=False, help_text='Id from third party service.', max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('num_of_rooms', models.PositiveIntegerField(null=True)),
                ('district', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'apartment_advt',
            },
        ),
    ]
