# Generated by Django 2.2.2 on 2019-07-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_advt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentadvt',
            name='publishing_date',
            field=models.DateTimeField(null=True),
        ),
    ]
